version: 1.0.{build}
branches:
  only:
  - master

configuration: Test

before_build:
  - nuget restore 

build:
  verbosity: minimal
  project: lb1.sln

test:
  assemblies:
    - '**\*.Test.dll'
artifacts:  
- path: '**\*.nupkg'
  name: NuGet